apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: "redis-enterprise"
  namespace: redis
spec:
  nodes: 1
  persistentSpec:
    enabled: true
    storageClassName: "standard"
    volumeSize: 20Gi
  redisEnterpriseNodeResources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    repository: redislabs/redis
    versionTag: 7.2.4-72.rhel7-openshift